{
 "title": "Project Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "handler",
    "query": {
     "query": "label_values(prometheus_http_requests_total, handler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))*100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_build_info", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Kubernetes Build Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kubernetes_build_info" }
   ]
  },
  {
   "title": "HTTP Request Last Minute",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "increase(prometheus_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Pods Information",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kube_pod_info" }
   ]
  },
  {
   "title": "Node Information",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{pod_cidr}}" }
   ]
  },
  {
   "title": "Job failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kube_job_status_failed", "legendFormat": "job Status" },
    { "expr": "failed" }
   ]
  }
 ]
}